In [1]:
import numpy as np
import cv2 as cv

In [2]:

img=cv.imread("smallgray.png",0) # in the argument 0 means in grayscale 
                                # 1 means BGR scale
img

                                # Output
# The value in the matrix when it is higher it is nearer to white where white is 225

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

# Create an image from the numpy array

In [9]:
nArr=np.array([[100,0,125,225],
        [0,0,200,150],
        [100,90,50,150]])
cv.imwrite("newImage.png",nArr)
nArr

array([[100,   0, 125, 225],
       [  0,   0, 200, 150],
       [100,  90,  50, 150]])

In [13]:
nArr=cv.imread("newImage.png",0)
stk=np.hstack((nArr,nArr))
vStk=np.vstack((nArr,nArr))
print(stk)
print(vStk)

[[100   0 125 225 100   0 125 225]
 [  0   0 200 150   0   0 200 150]
 [100  90  50 150 100  90  50 150]]
[[100   0 125 225]
 [  0   0 200 150]
 [100  90  50 150]
 [100   0 125 225]
 [  0   0 200 150]
 [100  90  50 150]]
